name: Deploy to AWS EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: SSH into EC2
        run: |
          echo "$SSH_PRIVATE_KEY" | base64 --decode > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key ubuntu@${{ secrets.EC2_HOST }} 'bash -s' < deploy-script.sh

